import * as path from 'path';
import {
  Duration,
  RemovalPolicy,
  aws_apigateway as apigateway,
  aws_iam as iam,
  aws_lambda as lambda,
  aws_logs as logs,
} from 'aws-cdk-lib';
import {
  Gateway,
  GatewayAuthorizer,
  GatewayExceptionLevel,
  GatewayProtocol,
  MCPProtocolVersion,
  McpGatewaySearchType,
  SchemaDefinitionType,
  ToolDefinition,
  ToolSchema,
} from '@aws-cdk/aws-bedrock-agentcore-alpha';
import { Construct } from 'constructs';

export interface GatewayResourcesProps {
  readonly api: apigateway.RestApi;
  readonly toolFunction: lambda.Function;
  readonly stageName: string;
  readonly runtimeRole: iam.IRole;
  readonly removalPolicy: RemovalPolicy;
}

export interface GatewayResources {
  readonly agentCoreGateway: Gateway;
  readonly gatewayProxyFunction: lambda.Function;
  readonly gatewaysUrl: string;
  readonly mcpProxyUrl: string;
  readonly agentCoreGatewayUrl: string;
  readonly agentCoreGatewayArn: string;
}

export function createGatewayResources(
  scope: Construct,
  props: GatewayResourcesProps,
): GatewayResources {
  const agentCoreGateway = new Gateway(scope, 'PortfolioPlanningGateway', {
    gatewayName: `financial-planning-${props.stageName}`,
    description: 'MCP gateway for financial planning portfolio optimization tools.',
    authorizerConfiguration: GatewayAuthorizer.usingAwsIam(),
    exceptionLevel: GatewayExceptionLevel.DEBUG,
    protocolConfiguration: GatewayProtocol.mcp({
      supportedVersions: [MCPProtocolVersion.MCP_2025_06_18, MCPProtocolVersion.MCP_2025_03_26],
      searchType: McpGatewaySearchType.SEMANTIC,
      instructions:
        'Use these tools to inspect math-model inputs and outputs, retrieve the formulation, create governed input overrides, run the 16-week portfolio math model, and record override justifications.',
    }),
    tags: {
      app: 'financial-planning-backend',
      stage: props.stageName,
    },
  });

  agentCoreGateway.addLambdaTarget('PortfolioPlanningToolsTarget', {
    gatewayTargetName: 'portfolio-planning',
    description: 'Portfolio planning tools implemented by a Lambda target.',
    lambdaFunction: props.toolFunction,
    toolSchema: ToolSchema.fromInline(PORTFOLIO_PLANNING_TOOL_SCHEMA),
  });
  agentCoreGateway.grantInvoke(props.runtimeRole);

  const gatewayProxyLogGroup = new logs.LogGroup(scope, 'GatewayProxyLogGroup', {
    retention: logs.RetentionDays.ONE_MONTH,
    removalPolicy: props.removalPolicy,
  });

  const gatewayProxyFunction = new lambda.Function(scope, 'GatewayProxyFunction', {
    runtime: lambda.Runtime.PYTHON_3_11,
    architecture: lambda.Architecture.ARM_64,
    handler: 'index.handler',
    code: lambda.Code.fromAsset(path.join(__dirname, '..', 'lambda', 'gateway-proxy')),
    timeout: Duration.seconds(20),
    memorySize: 256,
    logGroup: gatewayProxyLogGroup,
    environment: {
      TOOL_FUNCTION_NAME: props.toolFunction.functionName,
      CORS_ALLOWED_ORIGINS: process.env.CORS_ALLOWED_ORIGINS ?? '*',
    },
  });

  props.toolFunction.grantInvoke(gatewayProxyFunction);

  const gatewaysResource = props.api.root.addResource('gateways');
  const gatewaysIamResource = gatewaysResource.addResource('iam');
  gatewaysIamResource.addMethod('GET', new apigateway.LambdaIntegration(gatewayProxyFunction), {
    authorizationType: apigateway.AuthorizationType.IAM,
  });

  const mcpResource = props.api.root.addResource('mcp');
  const mcpProxyResource = mcpResource.addResource('proxy');
  mcpProxyResource.addMethod('POST', new apigateway.LambdaIntegration(gatewayProxyFunction), {
    authorizationType: apigateway.AuthorizationType.IAM,
  });

  return {
    agentCoreGateway,
    gatewayProxyFunction,
    gatewaysUrl: `${props.api.url}gateways/iam`,
    mcpProxyUrl: `${props.api.url}mcp/proxy`,
    agentCoreGatewayUrl: agentCoreGateway.gatewayUrl ?? '',
    agentCoreGatewayArn: agentCoreGateway.gatewayArn,
  };
}

const PORTFOLIO_PLANNING_TOOL_SCHEMA: ToolDefinition[] = [
  {
    name: 'get_math_model_input',
    description: 'Return the model input payload used for a portfolio optimization run.',
    inputSchema: {
      type: SchemaDefinitionType.OBJECT,
      properties: {
        run_id: { type: SchemaDefinitionType.STRING },
      },
      required: ['run_id'],
    },
  },
  {
    name: 'get_math_model_output',
    description: 'Return the model output payload generated by a portfolio optimization run.',
    inputSchema: {
      type: SchemaDefinitionType.OBJECT,
      properties: {
        run_id: { type: SchemaDefinitionType.STRING },
      },
      required: ['run_id'],
    },
  },
  {
    name: 'override_math_model_input',
    description: 'Create a new model input by applying synthetic overrides to an existing input.',
    inputSchema: {
      type: SchemaDefinitionType.OBJECT,
      properties: {
        input_id: { type: SchemaDefinitionType.STRING },
        overrides: { type: SchemaDefinitionType.OBJECT },
        justification: { type: SchemaDefinitionType.STRING },
      },
      required: ['input_id'],
    },
  },
  {
    name: 'get_math_model_formulation',
    description: 'Return the synthetic math-model formulation for a portfolio optimization run.',
    inputSchema: {
      type: SchemaDefinitionType.OBJECT,
      properties: {
        run_id: { type: SchemaDefinitionType.STRING },
      },
      required: ['run_id'],
    },
  },
  {
    name: 'run_math_model',
    description: 'Run the synthetic portfolio optimization math model for a stored input payload.',
    inputSchema: {
      type: SchemaDefinitionType.OBJECT,
      properties: {
        input_id: { type: SchemaDefinitionType.STRING },
      },
      required: ['input_id'],
    },
  },
  {
    name: 'override_math_model',
    description: 'Record a governed manual override decision for a model input.',
    inputSchema: {
      type: SchemaDefinitionType.OBJECT,
      properties: {
        input_id: { type: SchemaDefinitionType.STRING },
        justification: { type: SchemaDefinitionType.STRING },
      },
      required: ['input_id', 'justification'],
    },
  },
];
