from __future__ import annotations

import hashlib
import json
import math
import os
import statistics
import time
from decimal import Decimal
from typing import Any

try:
    import boto3
    from botocore.exceptions import ClientError
except ModuleNotFoundError:
    boto3 = None

    class ClientError(Exception):
        pass

try:
    import yfinance as yf
except ModuleNotFoundError:
    yf = None


STOCKS = {
    "AAPL": {"sector": "Technology", "price": 188.4, "expected_return": 0.11, "risk": 0.18, "signal": "positive"},
    "MSFT": {"sector": "Technology", "price": 421.2, "expected_return": 0.12, "risk": 0.16, "signal": "positive"},
    "AMZN": {"sector": "Consumer", "price": 182.7, "expected_return": 0.10, "risk": 0.22, "signal": "neutral"},
    "NVDA": {"sector": "Technology", "price": 875.0, "expected_return": 0.18, "risk": 0.34, "signal": "positive"},
    "JPM": {"sector": "Financials", "price": 196.5, "expected_return": 0.08, "risk": 0.15, "signal": "neutral"},
    "JNJ": {"sector": "Healthcare", "price": 151.8, "expected_return": 0.05, "risk": 0.09, "signal": "defensive"},
    "XOM": {"sector": "Energy", "price": 118.2, "expected_return": 0.06, "risk": 0.20, "signal": "neutral"},
    "V": {"sector": "Financials", "price": 279.4, "expected_return": 0.09, "risk": 0.13, "signal": "positive"},
}

BASE_HOLDINGS = {
    "AAPL": 42,
    "MSFT": 18,
    "AMZN": 30,
    "NVDA": 8,
    "JPM": 35,
    "JNJ": 24,
    "XOM": 22,
    "V": 15,
}

DEFAULT_CASH = 18_500.0
DEFAULT_RISK_TARGET = "moderate"
DEFAULT_MODEL_ID = "us.amazon.nova-2-lite-v1:0"
MEMORY_STATE: dict[str, dict[str, Any]] = {}

TOOL_CATALOG = [
    {
        "name": "get_math_model_input",
        "gateway": "portfolio-planning",
        "description": "Return the model input payload used for a portfolio optimization run.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "run_id": {"type": "string"},
                "input_id": {"type": "string"},
            },
        },
    },
    {
        "name": "get_math_model_output",
        "gateway": "portfolio-planning",
        "description": "Return the model output payload generated by a portfolio optimization run.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "run_id": {"type": "string"},
                "input_id": {"type": "string"},
            },
        },
    },
    {
        "name": "override_math_model_input",
        "gateway": "portfolio-planning",
        "description": "Create a new model input by applying synthetic overrides to an existing input.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "input_id": {"type": "string"},
                "overrides": {"type": "object"},
                "justification": {"type": "string"},
            },
            "required": ["input_id"],
        },
    },
    {
        "name": "get_math_model_formulation",
        "gateway": "portfolio-planning",
        "description": "Return the synthetic math-model formulation for a portfolio optimization run.",
        "inputSchema": {
            "type": "object",
            "properties": {"run_id": {"type": "string"}},
            "required": ["run_id"],
        },
    },
    {
        "name": "trigger_math_model",
        "gateway": "portfolio-planning",
        "description": "Trigger the portfolio optimization math model for a stored input payload and return the run id.",
        "inputSchema": {
            "type": "object",
            "properties": {"input_id": {"type": "string"}},
            "required": ["input_id"],
        },
    },
    {
        "name": "get_math_model_status",
        "gateway": "portfolio-planning",
        "description": "Return completion status and metadata for a portfolio optimization model run.",
        "inputSchema": {
            "type": "object",
            "properties": {"run_id": {"type": "string"}},
            "required": ["run_id"],
        },
    },
    {
        "name": "override_math_model",
        "gateway": "portfolio-planning",
        "description": "Record a governed manual override decision for a model input.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "input_id": {"type": "string"},
                "justification": {"type": "string"},
            },
            "required": ["input_id", "justification"],
        },
    },
]


def _table():
    name = os.environ.get("STATE_TABLE_NAME")
    if not name or boto3 is None:
        return None
    return boto3.resource("dynamodb").Table(name)


def _response(status_code: int, body: dict[str, Any]) -> dict[str, Any]:
    return {
        "statusCode": status_code,
        "headers": {
            "content-type": "application/json",
            "access-control-allow-origin": "*",
            "access-control-allow-methods": "GET,POST,OPTIONS",
            "access-control-allow-headers": "Content-Type,Authorization,X-Amz-Date,X-Amz-Security-Token,X-Amz-Content-Sha256",
        },
        "body": json.dumps(_json_safe(body)),
    }


def _agentcore_context_tool_name(context: Any) -> str:
    client_context = getattr(context, "client_context", None)
    custom = getattr(client_context, "custom", None) if client_context is not None else None
    if not isinstance(custom, dict):
        return ""
    return str(custom.get("bedrockAgentCoreToolName") or "")


def _json_safe(value: Any) -> Any:
    if isinstance(value, Decimal):
        return float(value)
    if isinstance(value, dict):
        return {key: _json_safe(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_json_safe(item) for item in value]
    return value


def _stable_id(prefix: str, payload: dict[str, Any]) -> str:
    raw = json.dumps(payload, sort_keys=True, default=str)
    digest = hashlib.sha256(raw.encode("utf-8")).hexdigest()[:12]
    return f"{prefix}-{digest}"


def _put_state(item: dict[str, Any]) -> None:
    MEMORY_STATE[str(item["id"])] = _json_safe(item)
    table = _table()
    if table is None:
        return
    ttl = int(time.time()) + 30 * 24 * 60 * 60
    table.put_item(Item=json.loads(json.dumps({**item, "ttl": ttl, "updatedAt": int(time.time())}), parse_float=Decimal))


def _get_state(item_id: str) -> dict[str, Any] | None:
    if item_id in MEMORY_STATE:
        return _json_safe(MEMORY_STATE[item_id])
    table = _table()
    if table is None:
        return None
    try:
        result = table.get_item(Key={"id": item_id})
    except ClientError:
        return None
    item = result.get("Item")
    return _json_safe(item) if item else None


def _scan_state(item_type: str | None = None, limit: int = 25) -> list[dict[str, Any]]:
    memory_items = list(MEMORY_STATE.values())
    if item_type:
        memory_items = [item for item in memory_items if item.get("type") == item_type]

    table = _table()
    items = memory_items
    if table is not None:
        try:
            scan_args: dict[str, Any] = {}
            if item_type:
                scan_args.update(
                    {
                        "FilterExpression": "#type = :type",
                        "ExpressionAttributeNames": {"#type": "type"},
                        "ExpressionAttributeValues": {":type": item_type},
                    }
                )
            result = table.scan(**scan_args)
            items = result.get("Items", [])
        except ClientError:
            items = memory_items

    normalized = [_json_safe(item) for item in items]
    normalized.sort(key=lambda item: int(item.get("createdAt") or 0), reverse=True)
    return normalized[:limit]


def _iso_time(epoch_seconds: int | float | None) -> str:
    if not epoch_seconds:
        return ""
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(float(epoch_seconds)))


def _model_metadata() -> dict[str, Any]:
    return {
        "provider": "amazon-bedrock",
        "modelId": os.environ.get("MODEL_ID") or DEFAULT_MODEL_ID,
        "formulationVersion": "dummy-v2",
        "runtime": "synthetic-lambda",
        "disclaimer": "Synthetic template model metadata for logging and workflow validation only.",
    }


def _symbols(value: Any) -> list[str]:
    if isinstance(value, str):
        items = [item.strip().upper() for item in value.split(",")]
    elif isinstance(value, list):
        items = [str(item).strip().upper() for item in value]
    else:
        items = list(STOCKS)
    return [item for item in items if item in STOCKS] or list(STOCKS)


def _portfolio_id(args: dict[str, Any]) -> str:
    return str(args.get("portfolio_id") or "demo-growth-income").strip() or "demo-growth-income"


def _round(value: float) -> float:
    return round(float(value), 2)


def _snapshot(portfolio_id: str = "demo-growth-income", cash: float = DEFAULT_CASH) -> dict[str, Any]:
    positions = []
    for symbol, quantity in BASE_HOLDINGS.items():
        stock = STOCKS[symbol]
        value = quantity * stock["price"]
        positions.append(
            {
                "symbol": symbol,
                "quantity": quantity,
                "price": stock["price"],
                "marketValue": _round(value),
                "sector": stock["sector"],
                "expectedReturn": stock["expected_return"],
                "risk": stock["risk"],
                "dailyContext": _daily_context(symbol),
            }
        )
    invested = sum(item["marketValue"] for item in positions)
    return {
        "portfolioId": portfolio_id,
        "asOf": "synthetic-today",
        "cash": _round(cash),
        "positions": positions,
        "totalValue": _round(invested + cash),
        "assumption": "Prices, news, and holdings are synthetic placeholders until the daily financial-data pipeline is connected.",
    }


def _daily_context(symbol: str) -> str:
    stock = STOCKS[symbol]
    if stock["signal"] == "positive":
        return f"{symbol} has positive synthetic momentum with supportive daily news sentiment."
    if stock["signal"] == "defensive":
        return f"{symbol} is modeled as a defensive stabilizer with lower expected volatility."
    return f"{symbol} has neutral synthetic context; planner treats it as a diversification holding."


def _market_signal(expected_return: float, risk: float) -> str:
    if expected_return >= 0.10 and risk <= 0.30:
        return "positive"
    if expected_return < 0.02:
        return "defensive"
    return "neutral"


def _daily_context_from_feature(symbol: str, feature: dict[str, Any]) -> str:
    source = feature.get("source", "market-data")
    expected = float(feature.get("expectedReturn") or 0)
    risk = float(feature.get("risk") or 0)
    return (
        f"{symbol} uses {source} OHLCV history with annualized expected return "
        f"{expected:.2%} and annualized volatility {risk:.2%}. News sentiment is not connected yet."
    )


def _feature_from_history(symbol: str, rows: list[dict[str, Any]], sector: str | None = None) -> dict[str, Any]:
    closes = [float(row["close"]) for row in rows if row.get("close") is not None and float(row["close"]) > 0]
    if len(closes) < 2:
        raise ValueError(f"not enough close prices for {symbol}")
    returns = [(closes[index] / closes[index - 1]) - 1 for index in range(1, len(closes)) if closes[index - 1] > 0]
    if not returns:
        raise ValueError(f"not enough return observations for {symbol}")
    volumes = [float(row.get("volume") or 0) for row in rows if row.get("volume") is not None]
    expected_return = statistics.mean(returns) * 252
    risk = statistics.stdev(returns) * math.sqrt(252) if len(returns) > 1 else 0.0
    last_row = rows[-1]
    return {
        "symbol": symbol,
        "source": "yfinance",
        "asOfDate": str(last_row.get("date") or time.strftime("%Y-%m-%d", time.gmtime())),
        "price": _round(closes[-1]),
        "expectedReturn": round(float(expected_return), 6),
        "risk": round(float(risk), 6),
        "averageDailyVolume": _round(statistics.mean(volumes)) if volumes else 0,
        "observations": len(closes),
        "sector": sector or STOCKS.get(symbol, {}).get("sector", "Unknown"),
        "signal": _market_signal(expected_return, risk),
        "summary": (
            f"{symbol} yfinance close=${_round(closes[-1]):,.2f}, "
            f"annualized return={expected_return:.2%}, volatility={risk:.2%}."
        ),
    }


def _fetch_yfinance_features(symbols: list[str], period: str = "1y") -> list[dict[str, Any]]:
    if yf is None:
        raise ValueError("yfinance is not installed in this Lambda package")
    features = []
    for symbol in symbols:
        ticker = yf.Ticker(symbol)
        history = ticker.history(period=period, interval="1d", auto_adjust=False)
        if history is None or history.empty:
            raise ValueError(f"yfinance returned no history for {symbol}")
        rows = []
        for index, row in history.tail(260).iterrows():
            close = row.get("Close")
            if close is None or str(close) == "nan":
                continue
            rows.append(
                {
                    "date": getattr(index, "strftime", lambda _fmt: str(index))("%Y-%m-%d"),
                    "open": float(row.get("Open")) if row.get("Open") == row.get("Open") else None,
                    "high": float(row.get("High")) if row.get("High") == row.get("High") else None,
                    "low": float(row.get("Low")) if row.get("Low") == row.get("Low") else None,
                    "close": float(close),
                    "volume": float(row.get("Volume")) if row.get("Volume") == row.get("Volume") else None,
                }
            )
        features.append(_feature_from_history(symbol, rows, STOCKS.get(symbol, {}).get("sector")))
    return features


def _snapshot_from_market_features(
    portfolio_id: str,
    cash: float,
    market_features: list[dict[str, Any]],
) -> dict[str, Any]:
    by_symbol = {str(item["symbol"]).upper(): item for item in market_features}
    positions = []
    for symbol, quantity in BASE_HOLDINGS.items():
        feature = by_symbol.get(symbol)
        if not feature:
            continue
        price = float(feature["price"])
        value = quantity * price
        positions.append(
            {
                "symbol": symbol,
                "quantity": quantity,
                "price": _round(price),
                "marketValue": _round(value),
                "sector": feature.get("sector") or STOCKS.get(symbol, {}).get("sector", "Unknown"),
                "expectedReturn": float(feature.get("expectedReturn") or 0),
                "risk": float(feature.get("risk") or 0),
                "dailyContext": _daily_context_from_feature(symbol, feature),
                "averageDailyVolume": feature.get("averageDailyVolume"),
                "dataSource": "yfinance",
            }
        )
    invested = sum(item["marketValue"] for item in positions)
    return {
        "portfolioId": portfolio_id,
        "asOf": max((item.get("asOfDate") or "" for item in market_features), default="unknown"),
        "cash": _round(cash),
        "positions": positions,
        "totalValue": _round(invested + cash),
        "assumption": "Market prices and risk/return estimates are derived from yfinance OHLCV history. News sentiment is not connected yet.",
    }


def _target_weight(stock: dict[str, Any], risk_target: str) -> float:
    expected_return = float(stock.get("expected_return", stock.get("expectedReturn", 0)))
    risk = float(stock.get("risk", 0.01))
    score = expected_return / max(risk, 0.01)
    if risk_target == "conservative":
        score *= 0.7 if risk > 0.18 else 1.3
    elif risk_target == "growth":
        score *= 1.35 if expected_return >= 0.10 else 0.75
    return max(score, 0.01)


def _build_trade_plan(
    portfolio_id: str,
    risk_target: str,
    cash_available: float,
    max_trade_value_per_week: float,
    model_payload: dict[str, Any] | None = None,
) -> dict[str, Any]:
    snapshot = model_payload.get("snapshot") if model_payload and isinstance(model_payload.get("snapshot"), dict) else _snapshot(portfolio_id, cash_available)
    total_value = snapshot["totalValue"]
    stock_inputs = {
        pos["symbol"]: {
            "expected_return": pos.get("expectedReturn", STOCKS.get(pos["symbol"], {}).get("expected_return", 0)),
            "risk": pos.get("risk", STOCKS.get(pos["symbol"], {}).get("risk", 0.01)),
            "price": pos.get("price", STOCKS.get(pos["symbol"], {}).get("price", 0)),
            "signal": _market_signal(float(pos.get("expectedReturn", 0)), float(pos.get("risk", 0))),
            "dailyContext": pos.get("dailyContext"),
        }
        for pos in snapshot.get("positions", [])
    }
    scores = {symbol: _target_weight(stock, risk_target) for symbol, stock in stock_inputs.items()}
    score_total = sum(scores.values())
    current_values = {pos["symbol"]: pos["marketValue"] for pos in snapshot["positions"]}
    trades = []

    for symbol, score in sorted(scores.items(), key=lambda item: item[1], reverse=True):
        target_value = total_value * score / score_total
        delta = target_value - current_values.get(symbol, 0)
        if abs(delta) < 800:
            continue
        weekly_value = max(-max_trade_value_per_week, min(max_trade_value_per_week, delta / 4))
        action = "BUY" if weekly_value > 0 else "SELL"
        price = float(stock_inputs[symbol].get("price") or 1)
        quantity = max(1, round(abs(weekly_value) / price))
        trades.append(
            {
                "symbol": symbol,
                "action": action,
                "weeklyQuantity": quantity,
                "weeklyTradeValue": _round(quantity * price),
                "reason": _trade_reason(symbol, action, risk_target, stock_inputs.get(symbol)),
            }
        )

    if not trades:
        trades.append(
            {
                "symbol": "MSFT",
                "action": "BUY",
                "weeklyQuantity": 1,
                "weeklyTradeValue": stock_inputs.get("MSFT", STOCKS["MSFT"]).get("price", STOCKS["MSFT"]["price"]),
                "reason": "Maintains the demo plan with a small high-quality technology allocation.",
            }
        )

    weeks = []
    value = total_value
    expected_weekly_return = {"conservative": 0.0025, "moderate": 0.004, "growth": 0.006}[risk_target]
    for week in range(1, 17):
        week_trades = [trade for index, trade in enumerate(trades) if index % 4 == (week - 1) % 4]
        net_cash_use = sum(
            trade["weeklyTradeValue"] if trade["action"] == "BUY" else -trade["weeklyTradeValue"]
            for trade in week_trades
        )
        value = value * (1 + expected_weekly_return)
        weeks.append(
            {
                "week": week,
                "targetPortfolioValue": _round(value),
                "plannedTrades": week_trades,
                "netCashUse": _round(net_cash_use),
                "reviewFocus": _review_focus(week),
            }
        )
    return {
        "portfolioId": portfolio_id,
        "riskTarget": risk_target,
        "startingValue": total_value,
        "expectedValueAtWeek16": weeks[-1]["targetPortfolioValue"],
        "expectedReturnPct16w": _round((weeks[-1]["targetPortfolioValue"] / total_value - 1) * 100),
        "weeks": weeks,
        "tradeRationale": trades,
    }


def _model_input_from_args(args: dict[str, Any]) -> dict[str, Any]:
    portfolio_id = _portfolio_id(args)
    risk_target = str(args.get("risk_target") or DEFAULT_RISK_TARGET).lower()
    if risk_target not in {"conservative", "moderate", "growth"}:
        raise ValueError("risk_target must be conservative, moderate, or growth")
    cash_available = float(args.get("cash_available") or DEFAULT_CASH)
    max_trade_value = float(args.get("max_trade_value_per_week") or 7_500.0)
    market_features = args.get("market_features") if isinstance(args.get("market_features"), list) else []
    snapshot = (
        _snapshot_from_market_features(portfolio_id, cash_available, market_features)
        if market_features
        else _snapshot(portfolio_id, cash_available)
    )
    market_context = (
        [
            {
                "symbol": item["symbol"],
                "sector": item.get("sector"),
                "signal": item.get("signal"),
                "expectedReturn": item.get("expectedReturn"),
                "risk": item.get("risk"),
                "summary": item.get("summary"),
                "averageDailyVolume": item.get("averageDailyVolume"),
                "source": "yfinance",
            }
            for item in market_features
        ]
        if market_features
        else get_market_context({"symbols": list(STOCKS)})["items"]
    )
    source = str(args.get("source") or ("yfinance-market-data" if market_features else "manual-or-synthetic"))
    payload = {
        "asOfDate": str(args.get("as_of_date") or time.strftime("%Y-%m-%d", time.gmtime())),
        "source": source,
        "portfolioId": portfolio_id,
        "riskTarget": risk_target,
        "cashAvailable": _round(cash_available),
        "maxTradeValuePerWeek": _round(max_trade_value),
        "planningHorizonWeeks": 16,
        "snapshot": snapshot,
        "marketContext": market_context,
        "constraints": {
            "maxTradeValuePerWeek": _round(max_trade_value),
            "allowedActions": ["BUY", "SELL", "HOLD"],
            "noShortSelling": True,
            "rebalanceCadence": "weekly",
        },
        "assumption": (
            "Market features are derived from yfinance OHLCV data. News and portfolio-account data are still template placeholders."
            if market_features
            else "Synthetic model input for workflow validation only."
        ),
    }
    input_id = _stable_id("model-input", payload)
    return {"id": input_id, "type": "model-input", "createdAt": int(time.time()), "payload": payload}


def _default_model_input() -> dict[str, Any]:
    return _model_input_from_args(
        {
            "portfolio_id": "demo-growth-income",
            "risk_target": DEFAULT_RISK_TARGET,
            "cash_available": DEFAULT_CASH,
            "max_trade_value_per_week": 7_500.0,
        }
    )


def _persist_model_input(args: dict[str, Any]) -> dict[str, Any]:
    model_input = _model_input_from_args(args)
    _put_state(model_input)
    return model_input


def _require_model_input(input_id: str) -> dict[str, Any]:
    if not input_id:
        raise ValueError("input_id is required")
    state = _get_state(input_id)
    if state and state.get("type") == "model-input":
        return state
    if input_id in {"demo-model-input", "default"} or input_id == _default_model_input()["id"]:
        return _default_model_input()
    raise ValueError(f"model input not found: {input_id}")


def _require_model_run(run_id: str) -> dict[str, Any]:
    if not run_id:
        raise ValueError("run_id is required")
    state = _get_state(run_id)
    if state and state.get("type") == "portfolio-optimization":
        return state
    if run_id.startswith("portfolio-plan-"):
        return _require_simulation({"simulation_id": run_id})
    raise ValueError(f"model run not found: {run_id}")


def _latest_run_for_input(input_id: str) -> dict[str, Any] | None:
    if not input_id:
        return None
    runs = [
        run
        for run in _scan_state("portfolio-optimization", 100)
        if str(run.get("inputId") or "") == input_id
    ]
    return runs[0] if runs else None


def _resolve_model_run_or_input(args: dict[str, Any]) -> tuple[dict[str, Any], str]:
    run_id = str(args.get("run_id") or args.get("simulation_id") or "").strip()
    input_id = str(args.get("input_id") or "").strip()
    if (run_id.startswith("model-input-") or run_id in {"demo-model-input", "default"}) and not input_id:
        input_id = run_id
        run_id = ""
    if run_id:
        run = _require_model_run(run_id)
        return run, str(run.get("inputId") or "")
    if input_id:
        _require_model_input(input_id)
        run = _latest_run_for_input(input_id)
        if run:
            return run, input_id
        raise ValueError(f"no model output found for input_id: {input_id}; call trigger_math_model first")
    raise ValueError("run_id or input_id is required")


def _model_formulation(risk_target: str = DEFAULT_RISK_TARGET) -> dict[str, Any]:
    return {
        "modelName": "synthetic-portfolio-optimizer",
        "version": "dummy-v2",
        "objective": "Maximize synthetic expected portfolio value over 16 weeks after risk and liquidity penalties.",
        "decisionVariables": [
            "trade_quantity[symbol, week]",
            "cash_balance[week]",
            "position_quantity[symbol, week]",
        ],
        "constraints": [
            "Trade value per week must not exceed maxTradeValuePerWeek.",
            "Cash balance must remain non-negative.",
            "No short selling: position_quantity must remain greater than or equal to zero.",
            "Trades may only use BUY, SELL, or HOLD actions.",
            "Planning horizon is fixed at 16 weekly periods.",
        ],
        "riskTarget": risk_target,
        "outputs": [
            "weekly trade plan",
            "expected portfolio value path",
            "liquidity usage",
            "symbol-level rationale",
        ],
        "disclaimer": "Synthetic formulation for UX and integration testing only; not financial advice.",
    }


def _trade_reason(symbol: str, action: str, risk_target: str, stock_input: dict[str, Any] | None = None) -> str:
    stock = stock_input or STOCKS[symbol]
    expected_return = float(stock.get("expected_return", stock.get("expectedReturn", 0)))
    signal = str(stock.get("signal") or "market-data")
    if action == "BUY":
        return (
            f"{symbol} scores well for {risk_target} planning because expected return is "
            f"{expected_return:.0%} with {signal} context."
        )
    return (
        f"{symbol} is reduced to free liquidity or rebalance sector exposure under the "
        f"{risk_target} risk target."
    )


def _review_focus(week: int) -> str:
    if week == 1:
        return "Confirm cash availability and execute only the first tranche."
    if week % 4 == 0:
        return "Monthly review: compare realized value against expected path and rerun if forecast error is material."
    return "Check adherence, liquidity, and whether daily market context changed the thesis."


def health_check() -> dict[str, Any]:
    return {
        "status": True,
        "stage": os.environ.get("STAGE", "unknown"),
        "runtime": "lambda",
        "gateways": ["portfolio-planning"],
        "toolCount": len(TOOL_CATALOG),
    }


def list_gateways() -> dict[str, Any]:
    return {
        "gateways": [
            {
                "id": "portfolio-planning",
                "name": "Portfolio Planning",
                "description": "Math-model input, output, formulation, run, and override tools backed by stored portfolio planning data.",
                "mcpUrl": "local://portfolio-planning",
                "authType": "iam-proxy",
                "sigv4Region": os.environ.get("AWS_REGION", "us-west-2"),
                "sigv4Service": "execute-api",
            }
        ]
    }


def list_tools(gateway: str | None = None) -> dict[str, Any]:
    tools = [tool for tool in TOOL_CATALOG if not gateway or tool["gateway"] == gateway]
    return {"tools": tools, "gateway": gateway or "all"}


def list_portfolios() -> dict[str, Any]:
    return {
        "portfolios": [
            {
                "portfolioId": "demo-growth-income",
                "name": "Demo Growth Income Portfolio",
                "baseCurrency": "USD",
                "planningHorizonWeeks": 16,
            }
        ]
    }


def get_market_context(args: dict[str, Any]) -> dict[str, Any]:
    symbols = _symbols(args.get("symbols"))
    return {
        "asOf": "synthetic-today",
        "items": [
            {
                "symbol": symbol,
                "sector": STOCKS[symbol]["sector"],
                "signal": STOCKS[symbol]["signal"],
                "expectedReturn": STOCKS[symbol]["expected_return"],
                "risk": STOCKS[symbol]["risk"],
                "summary": _daily_context(symbol),
            }
            for symbol in symbols
        ],
    }


def run_optimization(args: dict[str, Any]) -> dict[str, Any]:
    model_input = _persist_model_input(args)
    result = trigger_math_model({"input_id": model_input["id"]})
    simulation_id = result["run_id"]
    plan = result["model_output"]["plan"]
    return {
        "simulation_id": simulation_id,
        "run_id": simulation_id,
        "input_id": model_input["id"],
        "status": "COMPLETED",
        "summary": {
            "portfolioId": model_input["payload"]["portfolioId"],
            "riskTarget": model_input["payload"]["riskTarget"],
            "expectedReturnPct16w": plan["expectedReturnPct16w"],
            "expectedValueAtWeek16": plan["expectedValueAtWeek16"],
        },
        "nextStep": "Call get_math_model_input, get_math_model_output, get_math_model_status, get_math_model_formulation, override_math_model_input, or trigger_math_model.",
    }


def _require_simulation(args: dict[str, Any]) -> dict[str, Any]:
    simulation_id = str(args.get("simulation_id") or "").strip()
    if not simulation_id:
        raise ValueError("simulation_id is required")
    state = _get_state(simulation_id)
    if state:
        return state
    return run_optimization({"portfolio_id": "demo-growth-income", "risk_target": DEFAULT_RISK_TARGET})


def get_simulation_status(args: dict[str, Any]) -> dict[str, Any]:
    state = _require_simulation(args)
    return {
        "simulation_id": state.get("id") or state.get("simulation_id"),
        "status": state.get("status", "COMPLETED"),
        "createdAt": state.get("createdAt"),
        "inputs": state.get("inputs", {}),
    }


def get_simulation_results(args: dict[str, Any]) -> dict[str, Any]:
    state = _require_simulation(args)
    return {
        "simulation_id": state.get("id") or args.get("simulation_id"),
        "status": state.get("status", "COMPLETED"),
        "plan": state.get("plan", {}),
    }


def run_what_if(args: dict[str, Any]) -> dict[str, Any]:
    state = _require_simulation(args)
    plan = state.get("plan", {})
    expected_value = float(plan.get("expectedValueAtWeek16", plan.get("startingValue", 0)))
    cash_available = float(args.get("cash_available") or state.get("inputs", {}).get("cashAvailable", DEFAULT_CASH))
    forecast_shock_pct = float(args.get("forecast_shock_pct") or 0)
    missed = _symbols(args.get("missed_trade_symbols")) if args.get("missed_trade_symbols") else []
    adjusted_value = expected_value * (1 + forecast_shock_pct / 100)
    liquidity_gap = max(0.0, 5_000.0 - cash_available)
    return {
        "simulation_id": state.get("id"),
        "scenario": {
            "cashAvailable": _round(cash_available),
            "forecastShockPct": forecast_shock_pct,
            "missedTradeSymbols": missed,
        },
        "impact": {
            "adjustedExpectedValueAtWeek16": _round(adjusted_value),
            "valueDeltaVsPlan": _round(adjusted_value - expected_value),
            "liquidityGap": _round(liquidity_gap),
            "adherenceRisk": "HIGH" if liquidity_gap > 0 or len(missed) >= 3 else "MEDIUM" if missed else "LOW",
        },
        "recommendation": "Rerun optimization if liquidity gap or forecast error persists for two weekly reviews.",
    }


def explain_trade_plan(args: dict[str, Any]) -> dict[str, Any]:
    state = _require_simulation(args)
    plan = state.get("plan", {})
    return {
        "simulation_id": state.get("id"),
        "explanation": [
            "The dummy optimizer scores each stock using expected return divided by risk.",
            "Risk target changes the score: conservative favors lower volatility, growth favors higher expected return.",
            "Trades are spread over 16 weeks to reduce liquidity pressure and allow weekly re-planning.",
        ],
        "tradeRationale": plan.get("tradeRationale", []),
        "limitations": [
            "This is synthetic template logic, not financial advice.",
            "The future math-model pipeline should replace this Lambda handler with an MCP-exposed optimizer.",
        ],
    }


def record_weekly_review(args: dict[str, Any]) -> dict[str, Any]:
    state = _require_simulation(args)
    week = int(args.get("week") or 1)
    review_id = _stable_id("review", {"simulation_id": state.get("id"), "week": week, "notes": args.get("notes", "")})
    review = {
        "id": review_id,
        "type": "weekly-review",
        "simulationId": state.get("id"),
        "week": week,
        "actualCash": _round(float(args.get("actual_cash") or DEFAULT_CASH)),
        "actualValue": _round(float(args.get("actual_value") or state.get("plan", {}).get("startingValue", 0))),
        "notes": str(args.get("notes") or ""),
        "status": "RECORDED",
    }
    _put_state(review)
    return review


def generate_weekly_report(args: dict[str, Any]) -> dict[str, Any]:
    state = _require_simulation(args)
    plan = state.get("plan", {})
    week = int(args.get("week") or 1)
    remaining_weeks = [item for item in plan.get("weeks", []) if int(item.get("week", 0)) >= week]
    previous_id = str(args.get("previous_simulation_id") or "").strip()
    deviation = "No previous plan was provided."
    if previous_id:
        previous = _get_state(previous_id)
        if previous:
            prev_value = float(previous.get("plan", {}).get("expectedValueAtWeek16", 0))
            current_value = float(plan.get("expectedValueAtWeek16", 0))
            deviation = f"Current week-16 expected value differs from previous plan by ${_round(current_value - prev_value):,.2f}."
        else:
            deviation = "Previous plan id was provided but not found in synthetic state."
    return {
        "simulation_id": state.get("id"),
        "week": week,
        "title": f"Weekly Portfolio Plan Review - Week {week}",
        "summary": {
            "portfolioId": plan.get("portfolioId"),
            "riskTarget": plan.get("riskTarget"),
            "expectedReturnPct16w": plan.get("expectedReturnPct16w"),
            "expectedValueAtWeek16": plan.get("expectedValueAtWeek16"),
            "deviationFromPreviousPlan": deviation,
        },
        "next16WeekPlan": remaining_weeks[:16],
        "watchItems": [
            "Liquidity available for the next tranche of buy orders.",
            "Forecast drift versus actual portfolio value.",
            "Symbols with changed daily context from the financial-data table.",
        ],
        "disclaimer": "Synthetic template output for workflow and UX validation only; not financial advice.",
    }


def get_math_model_input(args: dict[str, Any]) -> dict[str, Any]:
    run_id = str(args.get("run_id") or args.get("simulation_id") or "").strip()
    input_id_arg = str(args.get("input_id") or "").strip()
    if (run_id.startswith("model-input-") or run_id in {"demo-model-input", "default"}) and not input_id_arg:
        input_id_arg = run_id
        run_id = ""
    run = _require_model_run(run_id) if run_id else {}
    input_id = input_id_arg or str(run.get("inputId") or run.get("input_id") or "").strip()
    if input_id:
        model_input = _require_model_input(input_id)
        payload = model_input.get("payload", {})
    else:
        payload = run.get("inputs", {})
        input_id = _stable_id("model-input", payload)
    return {
        "run_id": run.get("id") or run_id or None,
        "input_id": input_id,
        "model_input": payload,
        "disclaimer": (
            "Market prices and OHLCV-derived return/risk features are from yfinance. "
            "Holdings, cash, news context, and optimizer assumptions remain template/demo logic."
            if payload.get("source") == "yfinance-market-data"
            else "Synthetic model input for workflow validation only."
        ),
    }


def get_math_model_output(args: dict[str, Any]) -> dict[str, Any]:
    run, input_id = _resolve_model_run_or_input(args)
    model_output = run.get("modelOutput") or {
        "plan": run.get("plan", {}),
        "status": run.get("status", "COMPLETED"),
    }
    return {
        "run_id": run.get("id"),
        "input_id": input_id or run.get("inputId"),
        "model_output": model_output,
        "disclaimer": "Template optimizer output for workflow validation only; not financial advice.",
    }


def override_math_model_input(args: dict[str, Any]) -> dict[str, Any]:
    input_id = str(args.get("input_id") or "").strip()
    model_input = _require_model_input(input_id)
    overrides = args.get("overrides") if isinstance(args.get("overrides"), dict) else {}
    payload = {**model_input.get("payload", {}), **overrides}
    payload["sourceInputId"] = input_id
    payload["source"] = "manual-override"
    payload["asOfDate"] = str(payload.get("asOfDate") or time.strftime("%Y-%m-%d", time.gmtime()))
    payload["overrideJustification"] = str(args.get("justification") or "Synthetic input override for planning review.")
    new_input_id = _stable_id("model-input", payload)
    item = {
        "id": new_input_id,
        "type": "model-input",
        "createdAt": int(time.time()),
        "payload": payload,
        "sourceInputId": input_id,
        "override_math_model": {
            "overrides": overrides,
            "justification": payload["overrideJustification"],
        },
    }
    _put_state(item)
    return {
        "input_id": new_input_id,
        "source_input_id": input_id,
        "model_input": payload,
        "nextStep": "Call trigger_math_model with input_id to generate a new run.",
    }


def get_math_model_formulation(args: dict[str, Any]) -> dict[str, Any]:
    run_id = str(args.get("run_id") or args.get("simulation_id") or "").strip()
    run = _require_model_run(run_id)
    risk_target = str(run.get("inputs", {}).get("riskTarget") or DEFAULT_RISK_TARGET)
    return {
        "run_id": run.get("id") or run_id,
        "input_id": run.get("inputId"),
        "formulation": _model_formulation(risk_target),
    }


def trigger_math_model(args: dict[str, Any]) -> dict[str, Any]:
    input_id = str(args.get("input_id") or "").strip()
    model_input = _require_model_input(input_id)
    payload = model_input.get("payload", {})
    portfolio_id = str(payload.get("portfolioId") or "demo-growth-income")
    risk_target = str(payload.get("riskTarget") or DEFAULT_RISK_TARGET)
    cash_available = float(payload.get("cashAvailable") or DEFAULT_CASH)
    max_trade_value = float(payload.get("maxTradeValuePerWeek") or 7_500.0)
    plan = _build_trade_plan(portfolio_id, risk_target, cash_available, max_trade_value, payload)
    model_output = {
        "plan": plan,
        "solverStatus": "OPTIMAL",
        "objectiveValue": plan["expectedValueAtWeek16"],
        "formulationVersion": "dummy-v2",
    }
    run_id = _stable_id("model-run", {"input_id": input_id, "model_output": model_output})
    now = int(time.time())
    item = {
        "id": run_id,
        "type": "portfolio-optimization",
        "status": "COMPLETED",
        "createdAt": now,
        "createdAtIso": _iso_time(now),
        "completedAt": now,
        "completedAtIso": _iso_time(now),
        "inputId": input_id,
        "inputs": {
            "portfolioId": portfolio_id,
            "riskTarget": risk_target,
            "cashAvailable": cash_available,
            "maxTradeValuePerWeek": max_trade_value,
            "asOfDate": payload.get("asOfDate"),
            "source": payload.get("source"),
        },
        "modelUsed": _model_metadata(),
        "modelOutput": model_output,
        "plan": plan,
    }
    _put_state(item)
    return {
        "run_id": run_id,
        "simulation_id": run_id,
        "input_id": input_id,
        "status": "COMPLETED",
        "outputReady": True,
        "completedAtIso": _iso_time(now),
        "model_output": model_output,
        "nextStep": "Call get_math_model_status with run_id to check completion, or get_math_model_output to inspect results.",
    }


def run_math_model(args: dict[str, Any]) -> dict[str, Any]:
    """Compatibility alias for older prompts and pipeline calls."""
    return trigger_math_model(args)


def get_math_model_status(args: dict[str, Any]) -> dict[str, Any]:
    run_id = str(args.get("run_id") or args.get("simulation_id") or "").strip()
    run = _require_model_run(run_id)
    status = str(run.get("status") or "UNKNOWN")
    return {
        "run_id": run.get("id") or run_id,
        "input_id": run.get("inputId"),
        "status": status,
        "outputReady": status == "COMPLETED" and bool(run.get("modelOutput")),
        "createdAt": run.get("createdAt"),
        "createdAtIso": run.get("createdAtIso") or _iso_time(run.get("createdAt")),
        "completedAt": run.get("completedAt"),
        "completedAtIso": run.get("completedAtIso"),
        "solverStatus": run.get("modelOutput", {}).get("solverStatus"),
        "modelUsed": run.get("modelUsed") or _model_metadata(),
    }


def override_math_model(args: dict[str, Any]) -> dict[str, Any]:
    input_id = str(args.get("input_id") or "").strip()
    justification = str(args.get("justification") or "").strip()
    if not justification:
        raise ValueError("justification is required")
    _require_model_input(input_id)
    override_id = _stable_id("override_math_model", {"input_id": input_id, "justification": justification})
    item = {
        "id": override_id,
        "type": "model-input-override",
        "inputId": input_id,
        "justification": justification,
        "status": "RECORDED",
        "createdAt": int(time.time()),
    }
    _put_state(item)
    return item


def create_weekly_model_run(args: dict[str, Any] | None = None) -> dict[str, Any]:
    args = args or {}
    created_at = int(time.time())
    input_args = {
        "portfolio_id": args.get("portfolio_id") or "demo-growth-income",
        "risk_target": args.get("risk_target") or DEFAULT_RISK_TARGET,
        "cash_available": args.get("cash_available") or DEFAULT_CASH,
        "max_trade_value_per_week": args.get("max_trade_value_per_week") or 7_500.0,
        "as_of_date": args.get("as_of_date") or time.strftime("%Y-%m-%d", time.gmtime(created_at)),
        "source": args.get("source") or "weekly-data-pipeline",
    }
    model_input = _persist_model_input(input_args)
    run = trigger_math_model({"input_id": model_input["id"]})
    return {
        "status": "COMPLETED",
        "input_id": model_input["id"],
        "run_id": run["run_id"],
        "createdAt": created_at,
        "createdAtIso": _iso_time(created_at),
        "source": input_args["source"],
    }


def fetch_market_data(args: dict[str, Any] | None = None) -> dict[str, Any]:
    args = args or {}
    symbols = _symbols(args.get("symbols") or os.environ.get("TICKER_UNIVERSE"))
    period = str(args.get("period") or "1y")
    created_at = int(time.time())
    features = _fetch_yfinance_features(symbols, period)
    as_of = max((item.get("asOfDate") or "" for item in features), default=time.strftime("%Y-%m-%d", time.gmtime()))
    batch_id = _stable_id("market-data-batch", {"provider": "yfinance", "as_of": as_of, "symbols": symbols})
    for feature in features:
        _put_state(
            {
                "id": f"market-data-{feature['symbol']}-{feature['asOfDate']}",
                "type": "market-data",
                "provider": "yfinance",
                "symbol": feature["symbol"],
                "createdAt": created_at,
                "createdAtIso": _iso_time(created_at),
                "payload": feature,
            }
        )
    batch = {
        "id": batch_id,
        "type": "market-data-batch",
        "provider": "yfinance",
        "createdAt": created_at,
        "createdAtIso": _iso_time(created_at),
        "asOfDate": as_of,
        "symbols": symbols,
        "items": features,
    }
    _put_state(batch)
    return {
        "batch_id": batch_id,
        "provider": "yfinance",
        "asOfDate": as_of,
        "symbols": symbols,
        "items": features,
        "createdAt": created_at,
        "createdAtIso": _iso_time(created_at),
    }


def create_market_data_model_run(args: dict[str, Any] | None = None) -> dict[str, Any]:
    args = args or {}
    market_data = fetch_market_data(args)
    created_at = int(time.time())
    model_input = _persist_model_input(
        {
            "portfolio_id": args.get("portfolio_id") or "demo-growth-income",
            "risk_target": args.get("risk_target") or DEFAULT_RISK_TARGET,
            "cash_available": args.get("cash_available") or DEFAULT_CASH,
            "max_trade_value_per_week": args.get("max_trade_value_per_week") or 7_500.0,
            "as_of_date": market_data["asOfDate"],
            "source": "yfinance-market-data",
            "market_features": market_data["items"],
        }
    )
    run = trigger_math_model({"input_id": model_input["id"]})
    return {
        "status": "COMPLETED",
        "provider": "yfinance",
        "market_data_batch_id": market_data["batch_id"],
        "input_id": model_input["id"],
        "run_id": run["run_id"],
        "createdAt": created_at,
        "createdAtIso": _iso_time(created_at),
        "source": "yfinance-market-data",
    }


def list_model_runs(args: dict[str, Any] | None = None) -> dict[str, Any]:
    args = args or {}
    limit = int(args.get("limit") or 10)
    input_limit = int(args.get("inputLimit") or args.get("input_limit") or 50)
    runs = _scan_state("portfolio-optimization", limit)
    model_inputs = _scan_state("model-input", input_limit)
    if not runs:
        seed = create_weekly_model_run({"source": "bootstrap-synthetic-seed"})
        runs = [_get_state(seed["run_id"]) or {}]

    items = []
    runs_by_input: dict[str, list[dict[str, Any]]] = {}
    for run in runs:
        plan = run.get("plan") or run.get("modelOutput", {}).get("plan", {})
        inputs = run.get("inputs", {})
        input_id = str(run.get("inputId") or "")
        model_input = _get_state(input_id) if input_id else None
        input_payload = model_input.get("payload", {}) if model_input else {}
        items.append(
            {
                "run_id": run.get("id"),
                "input_id": input_id,
                "status": run.get("status", "UNKNOWN"),
                "outputReady": run.get("status") == "COMPLETED" and bool(run.get("modelOutput")),
                "createdAt": run.get("createdAt"),
                "createdAtIso": run.get("createdAtIso") or _iso_time(run.get("createdAt")),
                "completedAt": run.get("completedAt"),
                "completedAtIso": run.get("completedAtIso"),
                "portfolioId": inputs.get("portfolioId") or input_payload.get("portfolioId"),
                "riskTarget": inputs.get("riskTarget") or input_payload.get("riskTarget"),
                "asOfDate": inputs.get("asOfDate") or input_payload.get("asOfDate"),
                "source": inputs.get("source") or input_payload.get("source"),
                "cashAvailable": inputs.get("cashAvailable") or input_payload.get("cashAvailable"),
                "expectedValueAtWeek16": plan.get("expectedValueAtWeek16"),
                "expectedReturnPct16w": plan.get("expectedReturnPct16w"),
                "solverStatus": run.get("modelOutput", {}).get("solverStatus"),
                "modelUsed": run.get("modelUsed") or _model_metadata(),
                "description": (
                    f"{inputs.get('riskTarget') or input_payload.get('riskTarget', 'moderate')} plan for "
                    f"{inputs.get('portfolioId') or input_payload.get('portfolioId', 'demo-growth-income')}"
                ),
            }
        )
        if input_id:
            runs_by_input.setdefault(input_id, []).append(items[-1])

    input_items = []
    for model_input in model_inputs:
        input_id = str(model_input.get("id") or "")
        payload = model_input.get("payload", {}) if isinstance(model_input.get("payload"), dict) else {}
        snapshot = payload.get("snapshot", {}) if isinstance(payload.get("snapshot"), dict) else {}
        linked_runs = runs_by_input.get(input_id, [])
        input_items.append(
            {
                "input_id": input_id,
                "createdAt": model_input.get("createdAt"),
                "createdAtIso": model_input.get("createdAtIso") or _iso_time(model_input.get("createdAt")),
                "portfolioId": payload.get("portfolioId"),
                "riskTarget": payload.get("riskTarget"),
                "asOfDate": payload.get("asOfDate"),
                "source": payload.get("source"),
                "cashAvailable": payload.get("cashAvailable"),
                "totalValue": snapshot.get("totalValue"),
                "latest_run_id": linked_runs[0]["run_id"] if linked_runs else None,
                "latest_run_status": linked_runs[0].get("status") if linked_runs else None,
                "latest_run_output_ready": linked_runs[0].get("outputReady") if linked_runs else False,
                "run_ids": [linked_run["run_id"] for linked_run in linked_runs if linked_run.get("run_id")],
                "run_count": len(linked_runs),
            }
        )

    return {
        "items": items,
        "inputs": input_items,
        "latest": items[0] if items else None,
        "count": len(items),
        "inputCount": len(input_items),
        "storage": {
            "table": os.environ.get("STATE_TABLE_NAME") or "in-memory-local",
            "recordTypes": [
                "market-data",
                "market-data-batch",
                "model-input",
                "portfolio-optimization",
                "model-input-override",
            ],
        },
    }


def _handle_http(event: dict[str, Any]) -> dict[str, Any]:
    method = str(event.get("httpMethod") or event.get("requestContext", {}).get("http", {}).get("method") or "GET").upper()
    path = str(event.get("path") or event.get("rawPath") or "")
    if method == "OPTIONS":
        return _response(200, {})
    if path.endswith("/planning/runs") and method == "GET":
        query = event.get("queryStringParameters") or {}
        return _response(200, list_model_runs(query))
    if path.endswith("/planning/runs") and method == "POST":
        raw_body = event.get("body") or "{}"
        body = json.loads(raw_body) if isinstance(raw_body, str) and raw_body.strip() else {}
        if body.get("input_id"):
            return _response(200, trigger_math_model({"input_id": body["input_id"]}))
        if body.get("source") == "yfinance-market-data":
            return _response(200, create_market_data_model_run(body))
        return _response(200, create_weekly_model_run(body))
    return _response(404, {"error": f"unknown route: {method} {path}"})


TOOL_HANDLERS = {
    "healthCheck": lambda args: health_check(),
    "listGateways": lambda args: list_gateways(),
    "listTools": lambda args: list_tools(args.get("gateway")),
    "get_math_model_input": get_math_model_input,
    "get_math_model_output": get_math_model_output,
    "override_math_model_input": override_math_model_input,
    "get_math_model_formulation": get_math_model_formulation,
    "trigger_math_model": trigger_math_model,
    "get_math_model_status": get_math_model_status,
    "run_math_model": run_math_model,
    "override_math_model": override_math_model,
    "listModelRuns": lambda args: list_model_runs(args),
    "createWeeklyModelRun": lambda args: create_weekly_model_run(args),
    "fetchMarketData": lambda args: fetch_market_data(args),
    "createMarketDataModelRun": lambda args: create_market_data_model_run(args),
}


def _normalize_tool_name(tool_name: str) -> str:
    name = str(tool_name or "").strip()
    if name in TOOL_HANDLERS:
        return name
    for delimiter in ("___", "__"):
        if delimiter in name:
            candidate = name.split(delimiter, 1)[1]
            if candidate in TOOL_HANDLERS:
                return candidate
    for known in TOOL_HANDLERS:
        if name.endswith(known):
            return known
    return name


def invoke_tool(tool_name: str, args: dict[str, Any]) -> dict[str, Any]:
    normalized = _normalize_tool_name(tool_name)
    handler = TOOL_HANDLERS.get(normalized)
    if handler is None:
        raise ValueError(f"unknown tool: {tool_name}")
    return handler(args)


def handler(event: dict[str, Any], context: Any) -> dict[str, Any]:
    try:
        if event.get("source") == "financial-planning.weekly-data-pipeline":
            return _json_safe(create_weekly_model_run(event.get("detail") or event))

        if event.get("source") == "financial-planning.market-data-pipeline":
            return _json_safe(create_market_data_model_run(event.get("detail") or event))

        if event.get("httpMethod") or event.get("rawPath") or event.get("requestContext", {}).get("http"):
            return _handle_http(event)

        gateway_tool_name = _agentcore_context_tool_name(context)
        if gateway_tool_name:
            return _json_safe(invoke_tool(gateway_tool_name, event))

        tool_name = event.get("tool") or event.get("name")
        args = event.get("arguments") or event.get("args") or {}
        if not tool_name:
            return _response(400, {"error": "tool is required"})
        return _response(200, invoke_tool(str(tool_name), args))
    except Exception as exc:
        if _agentcore_context_tool_name(context):
            return {"error": str(exc)}
        return _response(400, {"error": str(exc)})
